exports.CREATETICKETTYPE = "CREATETICKETTYPE";
exports.EDITTICKETTYPE = "EDITTICKETTYPE";
exports.LISTTICKETTYPE = "LISTTICKETTYPE";
exports.DELETETICKETTYPE = "DELETETICKETTYPE";

exports.TICKETDEFAULTACTIONS = "TICKETDEFAULTACTIONS";
exports.CREATETICKETACTION = "CREATETICKETACTION";
exports.EDITTICKETACTION = "EDITTICKETACTION";
exports.LISTTICKETACTION = "LISTTICKETACTION";
exports.DELETETICKETACTION = "DELETETICKETACTION";

exports.CREATETICKET = "CREATETICKET";
exports.ASSIGNTICKET = "ASSIGNTICKET";
exports.UPDATEREPORTER = "UPDATEREPORTER";
exports.ACCEPTTICKET = "ACCEPTTICKET";
exports.HOLDUNHOLDTICKET = "HOLDUNHOLDTICKET";
exports.CLOSETICKET = "CLOSETICKET";
exports.REOPENTICKET = "REOPENTICKET";
exports.TAKEACTION = "TAKEACTION";
exports.TICKETDETAILS = "TICKETDETAILS";
exports.LISTTICKETS = "LISTTICKETS";
