"use strict";

exports.CREATETICKETTYPE = "CREATETICKETTYPE";
exports.EDITTICKETTYPE = "EDITTICKETTYPE";
exports.LISTTICKETTYPE = "LISTTICKETTYPE";
exports.DELETETICKETTYPE = "DELETETICKETTYPE";

exports.CREATETICKETACTION = "CREATETICKETACTION";
exports.EDITTICKETACTION = "EDITTICKETACTION";
exports.LISTTICKETACTION = "LISTTICKETACTION";
exports.DELETETICKETACTION = "DELETETICKETACTION";